### ISSUE TITLE
Update library to work on Python 3.8.1 and above

### ISSUE THREAD

**Issue by scrazzz** [LordOfPolls/Rule34-API-Wrapper#18]
# The Problem
This library doesn't support Python 3.8.2 as it installs asyncio which causes an error.
# Solution
By removing `asyncio` from `install_requires=['asyncio', 'aiohttp']` it should fix this problem.

**Comment by LordOfPolls** [comment]
Im unable to replicate this issue. 

After running ``pip install rule34`` on a fresh install of python 3.8.2 (as per your issue) it installs without error. Please can you provide a traceback of the error, and what platform you're running on.

**Comment by scrazzz** [comment]
This is the full traceback of the error.
I guess the error is raised because I am running this on repl.it.
![IMG_0150](https://user-images.githubusercontent.com/70033559/97111149-33156600-16ee-11eb-9588-0ae2540c7633.jpeg)

**Comment by LordOfPolls** [comment]
At least from my testing, this seams to be a repl.it specific issue. As testing with clean installs on Linux and windows results in no issues. 

The issue seems to be specific to repl.it, and as i dont use that website, I'm unsure on a resolution. As for your original solution, that line is executed during setup and install, not during the import. Repl.it only fails when trying to import rule34.

**Comment by scrazzz** [comment]
There was another library which installs asyncio as it is required. I reached out to the dev about it and said that I was facing this same issue with asyncio. He updated the library to not install asyncio which fixed the issue. 

I'm unsure if anyone else has faced this issue. But I don't think there will be an issue even if `asyncio` is removed from `install_requires` (*I think*).

Anyways, now I'm pretty sure it's a problem with repl.it, I've found an alternative solution by adding the rule34 source folder into my python file directory which works fine. I hope that's okay 😬

Thank you for helping :)
